# -------HTTP REST CLIENT -------
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@login_base = login.microsoftonline.com/{{TENANT_ID}}
@oauth_token_host = {{login_base}}/oauth2/v2.0/token
@scopes = {{CLIENT_ID}}/.default openid profile offline_access
@AUTH_CODE = 0.ARoAv4j5cvGGr0GRqy180BHbR5OgmrUHGY5IuDHSKk3z1L4aAJs.AQABAAIAAAD--DLA3VO7QrddgJg7Wevr6Q3qsxPWbdlWKG-O58siJViIBMCB88wzxNZ85yRzthwbe3MGbwb84z26DhxxkAG9HDoxgb1TjP4NYa9Ou9VhHB_vOAhhAobfZ5yAaNmqB_Dpi0A0PiO-spekQpDRmZu9E3qamqVho53IT4jlFkCnYeC-DbSMc8rd4zlTC4OiXIXb6bzorQRRT7xUiiNv73T7NWyLcJw_iGJ1oVd9R6rqQ2SVUCBW2j1Ot26kTZnAMqwnSuSmRDVaNmYtmNeNJtZEFopQ98sCSqj4G34fm3r83F78q2gSlvAYeeh3wvaeO3Iq4iFshesXwpPXJV4ntkHgtEjtb28oOto1GAUdNPdQ9L-KZBUCJQCvfkg3t_Im6NfcHKI1qyX9hF1FvDha06WHxzx-HV5-lk-wH0hKcCr4gWxLE1ZXQaqNes_sNZIuhRNpiczssl7lmMI0Vpm_nkfNk-13JVUsqHWqXIKJucTC9GSOYcnECZ7qeuNZC1iCBve75WVJGprvPVU8pekh9qxQ9EUg6JZJXAhBVZ7PXvniRgA720Fv6r9eYzkWOlaAsMIvoc-qHP97jDHgpidYqM0kCeznuQ7aPLM8CSDKDqIcqGk88Rcz-C52-hf7nUaIyDeFZi3v1sZbp1wLeavDEACZcW5SrXtznyaUJcBOFbb9OC_0HTtAg9SQaBsvMA0LTJCNJpA_G-2eIsDWonFzlSY3tDBVM72hAKdD2soBAXEPkbNH6Ohr68mk1DFOHyNWBqRX2VPq6kcRPqsb0wUY50jFX-Vbjwu-VIETTMoNYUqt3vS_KoGfldeZ8YtALAqXRQpG-nmarnV2yETAfde_gcYq1OYFirjYIJOD6uHiPlXSV4zCH0IfVeqX7zIOJXwyhSS_n7N2Ikxg16ctuOtOZOQlIAA

# -----------------------
# OAUTH  authorization_code
# -----------------------
###
# @name authorize
POST https://{{oauth_token_host}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
&redirect_uri=https://{{OSDU_HOST}}/login/
&client_id={{CLIENT_ID}}
&client_secret={{CLIENT_SECRET}}
&scope={{scopes}}
&code={{AUTH_CODE}}


# -----------------------
# OAUTH  refresh_token
# -----------------------
###
# @name refresh
POST https://{{oauth_token_host}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token
&client_id={{CLIENT_ID}}
&client_secret={{CLIENT_SECRET}}
&refresh_token={{authorize.response.body.refresh_token}}
&scope={{scopes}}


# -----------------------
# API (Variables)
# -----------------------
###
@access_token = {{refresh.response.body.access_token}}
