---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: self-managed-base
  namespace: osdu-azure
spec:
  values:
    fullnameOverride: osdu-svc
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 3f57194b-d0f0-4a78-a94a-619f5fad9aec
      resourcegroup: osdu-self-cplcggbc-ljwf-rg
      identity: osdu-self-cplcggbc-ljwf-osdu-identity
      identity_id: ca8ef5c0-4594-4c7d-89db-cfd8145ff359
      keyvault: osdu-self-cplcgg-ljwf-kv
      appid: b59aa093-1907-488e-b831-d22a4df3d4be
      oidAuthEnabled: false
    resourceLimits:
      defaultCpuRequests: "100m"
      defaultMemoryRequests: "800Mi"
      defaultCpuLimits: "1000m"
      defaultMemoryLimits: "2Gi"
    identity:
      name: osdu-identity
